import { defineConfig } from "orval";

export default defineConfig({
  "lms-api": {
    input: {
      target: process.env.ORVAL_INPUT_URL || "http://localhost:3000/docs-json",
      validation: false,
    },
    output: {
      mode: "tags-split",
      target: "./src/services/api/generated",
      schemas: "./src/services/api/generated/model",
      client: "react-query",
      httpClient: "fetch",
      clean: ["!custom-fetch.ts"],
      override: {
        mutator: {
          path: "./src/services/api/generated/custom-fetch.ts",
          name: "customFetch",
        },
        query: {
          useQuery: true,
          useSuspenseQuery: false,
          useInfinite: true,
          useInfiniteQueryParam: "page",
          signal: true,
        },
        header: () =>
          [
            "// AUTO-GENERATED by Orval — DO NOT EDIT",
            "// Regenerate with: npm run api:generate",
            "// @ts-nocheck",
            "/* eslint-disable */",
          ].join("\n"),
      },
    },
  },
});
