import type { StaffDashboardData } from "../types";

/**
 * Demo data for the staff dashboard.
 * Used as fallback when API endpoints have not returned data yet,
 * or when individual endpoints fail (safeFetch pattern).
 */
export const demoStaffDashboard: StaffDashboardData = {
  profile: {
    id: "1",
    name: "Muhammad Ali Khan",
    photo: undefined,
    staffId: "STF-2025-001",
    role: "Senior Teacher",
    department: "Mathematics",
    primaryBranch: "Main Campus",
    branches: [
      { id: "1", name: "Main Campus", assignedClasses: 4 },
      { id: "2", name: "City Branch", assignedClasses: 2 },
    ],
  },
  todaySchedule: [
    {
      id: "1",
      subject: "Mathematics",
      className: "Grade 10",
      section: "A",
      startTime: "08:00",
      endTime: "08:45",
      room: "Room 201",
      isCurrent: false,
      isNext: false,
    },
    {
      id: "2",
      subject: "Mathematics",
      className: "Grade 9",
      section: "B",
      startTime: "08:50",
      endTime: "09:35",
      room: "Room 203",
      isCurrent: true,
      isNext: false,
    },
    {
      id: "3",
      subject: "Mathematics",
      className: "Grade 10",
      section: "B",
      startTime: "09:40",
      endTime: "10:25",
      room: "Room 201",
      isCurrent: false,
      isNext: true,
    },
    {
      id: "4",
      subject: "Mathematics",
      className: "Grade 8",
      section: "A",
      startTime: "10:45",
      endTime: "11:30",
      room: "Room 105",
      isCurrent: false,
      isNext: false,
    },
    {
      id: "5",
      subject: "Mathematics",
      className: "Grade 11",
      section: "A",
      startTime: "11:35",
      endTime: "12:20",
      room: "Room 302",
      isCurrent: false,
      isNext: false,
    },
  ],
  attendance: {
    percentage: 95.2,
    totalDays: 120,
    presentDays: 114,
    absentDays: 3,
    lateDays: 3,
    todayCheckIn: "07:45 AM",
    todayCheckOut: undefined,
    todayStatus: "present",
    leaveBalance: [
      { type: "Casual", total: 12, used: 3, remaining: 9 },
      { type: "Sick", total: 10, used: 2, remaining: 8 },
      { type: "Earned", total: 15, used: 0, remaining: 15 },
    ],
  },
  assignedClasses: [
    {
      id: "1",
      className: "Grade 10",
      section: "A",
      subject: "Mathematics",
      studentCount: 35,
    },
    {
      id: "2",
      className: "Grade 10",
      section: "B",
      subject: "Mathematics",
      studentCount: 32,
    },
    {
      id: "3",
      className: "Grade 9",
      section: "B",
      subject: "Mathematics",
      studentCount: 38,
    },
    {
      id: "4",
      className: "Grade 8",
      section: "A",
      subject: "Mathematics",
      studentCount: 40,
    },
    {
      id: "5",
      className: "Grade 11",
      section: "A",
      subject: "Mathematics",
      studentCount: 28,
    },
  ],
  pendingTasks: [
    {
      type: "marks_entry",
      label: "Marks Entry Pending",
      count: 3,
      href: "/admin-panel/exams",
    },
    {
      type: "attendance",
      label: "Attendance to Mark",
      count: 2,
      href: "/admin-panel/attendance",
    },
    {
      type: "leave_approval",
      label: "Leave Approvals",
      count: 5,
      href: "/admin-panel/staff/leaves",
    },
  ],
  latestSalarySlip: {
    id: "1",
    month: "January",
    year: 2025,
    netPay: 85000,
    totalEarnings: 95000,
    totalDeductions: 10000,
    status: "paid",
    paidAt: "2025-01-31",
  },
  notices: [
    {
      id: "1",
      title: "Staff Meeting - February 5th",
      date: "2025-01-28",
      isRead: false,
      content:
        "All staff members are requested to attend the monthly meeting...",
    },
    {
      id: "2",
      title: "Mid-Term Exam Duty Schedule Released",
      date: "2025-01-25",
      isRead: false,
    },
    {
      id: "3",
      title: "Annual Sports Day Volunteers Needed",
      date: "2025-01-22",
      isRead: true,
    },
    {
      id: "4",
      title: "Salary Revision Notification",
      date: "2025-01-18",
      isRead: true,
    },
  ],
};
