import type { StudentDashboardData } from "../types";

/**
 * Demo data for the student dashboard.
 * Used as fallback when API endpoints have not returned data yet,
 * or when individual endpoints fail (safeFetch pattern).
 */
export const demoStudentDashboard: StudentDashboardData = {
  profile: {
    id: "1",
    name: "Ahmed Hassan",
    photo: undefined,
    studentId: "STU-2025-0042",
    className: "Grade 10",
    section: "A",
    academicYear: "2024-2025",
  },
  attendance: {
    percentage: 92.5,
    totalDays: 120,
    presentDays: 111,
    absentDays: 5,
    lateDays: 4,
    monthlyBreakdown: [
      { month: "Sep", percentage: 95 },
      { month: "Oct", percentage: 90 },
      { month: "Nov", percentage: 93 },
      { month: "Dec", percentage: 88 },
      { month: "Jan", percentage: 95 },
      { month: "Feb", percentage: 92 },
    ],
  },
  fees: {
    totalFee: 85000,
    paidAmount: 60000,
    pendingAmount: 25000,
    nextDueDate: "2025-02-15",
    nextDueAmount: 12500,
    recentPayments: [
      {
        id: "1",
        amount: 12500,
        date: "2025-01-10",
        method: "Bank Transfer",
        challanNumber: "CHN-20250110-001",
      },
      {
        id: "2",
        amount: 12500,
        date: "2024-12-05",
        method: "Online",
        challanNumber: "CHN-20241205-002",
      },
    ],
  },
  upcomingExams: [
    {
      id: "1",
      name: "Mid-Term Examinations",
      subject: "Mathematics",
      date: "2025-02-20",
      time: "09:00 AM",
      examType: "midterm",
    },
    {
      id: "2",
      name: "Mid-Term Examinations",
      subject: "Physics",
      date: "2025-02-22",
      time: "09:00 AM",
      examType: "midterm",
    },
    {
      id: "3",
      name: "Mid-Term Examinations",
      subject: "English",
      date: "2025-02-24",
      time: "09:00 AM",
      examType: "midterm",
    },
  ],
  recentResults: {
    examName: "First Term Examinations",
    overallPercentage: 87.5,
    grade: "A",
    rank: 5,
    subjects: [
      {
        id: "1",
        examName: "First Term",
        subject: "Mathematics",
        marksObtained: 92,
        totalMarks: 100,
        grade: "A+",
        percentage: 92,
      },
      {
        id: "2",
        examName: "First Term",
        subject: "Physics",
        marksObtained: 85,
        totalMarks: 100,
        grade: "A",
        percentage: 85,
      },
      {
        id: "3",
        examName: "First Term",
        subject: "English",
        marksObtained: 88,
        totalMarks: 100,
        grade: "A",
        percentage: 88,
      },
      {
        id: "4",
        examName: "First Term",
        subject: "Chemistry",
        marksObtained: 78,
        totalMarks: 100,
        grade: "B+",
        percentage: 78,
      },
    ],
  },
  materials: [
    {
      id: "1",
      title: "Chapter 5 - Quadratic Equations",
      subject: "Mathematics",
      uploadDate: "2025-01-28",
      fileType: "document",
    },
    {
      id: "2",
      title: "Newton's Laws of Motion - Notes",
      subject: "Physics",
      uploadDate: "2025-01-26",
      fileType: "document",
    },
    {
      id: "3",
      title: "Organic Chemistry Video Lecture",
      subject: "Chemistry",
      uploadDate: "2025-01-25",
      fileType: "video",
    },
  ],
  assignments: [
    {
      id: "1",
      title: "Solve Exercise 5.3",
      subject: "Mathematics",
      dueDate: "2025-02-05",
      status: "not_submitted",
    },
    {
      id: "2",
      title: "Lab Report - Friction",
      subject: "Physics",
      dueDate: "2025-02-03",
      status: "submitted",
    },
    {
      id: "3",
      title: "Essay: Climate Change",
      subject: "English",
      dueDate: "2025-02-08",
      status: "not_submitted",
    },
  ],
  notices: [
    {
      id: "1",
      title: "Mid-Term Exam Schedule Released",
      date: "2025-01-28",
      isRead: false,
      content: "The mid-term examination schedule has been published...",
    },
    {
      id: "2",
      title: "Annual Sports Day - February 15",
      date: "2025-01-25",
      isRead: false,
    },
    {
      id: "3",
      title: "Parent-Teacher Meeting",
      date: "2025-01-20",
      isRead: true,
    },
  ],
  timetable: [
    {
      id: "1",
      subject: "Mathematics",
      teacher: "Mr. Ali",
      startTime: "08:00",
      endTime: "08:45",
      room: "Room 201",
      isCurrent: false,
      isNext: false,
    },
    {
      id: "2",
      subject: "Physics",
      teacher: "Ms. Fatima",
      startTime: "08:50",
      endTime: "09:35",
      room: "Lab 3",
      isCurrent: true,
      isNext: false,
    },
    {
      id: "3",
      subject: "English",
      teacher: "Mrs. Khan",
      startTime: "09:40",
      endTime: "10:25",
      room: "Room 201",
      isCurrent: false,
      isNext: true,
    },
    {
      id: "4",
      subject: "Break",
      teacher: "",
      startTime: "10:25",
      endTime: "10:45",
      isCurrent: false,
      isNext: false,
    },
    {
      id: "5",
      subject: "Chemistry",
      teacher: "Dr. Ahmed",
      startTime: "10:45",
      endTime: "11:30",
      room: "Lab 1",
      isCurrent: false,
      isNext: false,
    },
    {
      id: "6",
      subject: "Urdu",
      teacher: "Ms. Noor",
      startTime: "11:35",
      endTime: "12:20",
      room: "Room 201",
      isCurrent: false,
      isNext: false,
    },
    {
      id: "7",
      subject: "Computer Science",
      teacher: "Mr. Saad",
      startTime: "12:25",
      endTime: "13:10",
      room: "IT Lab",
      isCurrent: false,
      isNext: false,
    },
  ],
};
